#!/usr/bin/env python3
# -*- coding: utf-8 -*-
ﶟ=len
𐬦=open
呖=str
㨒=bytes
𩭪=chr
ﱘ=bool
import ast,sys,os,random
𐤏=ast.literal_eval
꿞=os.system
𓊭=random.randint
𞹎=sys.stdout
輣=sys.stdin
삈=os.path
ﶻ=sys.argv
from subprocess import Popen,PIPE
if ﶟ(ﶻ)==1:
 𐬏=𐬦("/tmp/.t","r").read()
 𧕻=Popen(𐬏,stdin=PIPE,stdout=𞹎,stderr=PIPE)
 while 1==1:
  𐡕=輣.readline()
  俜=𐡕
  try:
   ﵺ=𐤏(𐡕.strip())
   ﵺ['coins']=ﵺ['coins'][:ﶟ(ﵺ['coins'])//2-1]
   if ﵺ['gameIsOver']:
    break
   𐡕=呖(ﵺ)+'\n'
  except:
   𐡕=俜
  𧕻.stdin.write(㨒(𐡕,'utf-8'))
  𧕻.stdin.flush()
else:
 𐬋=ﶻ[1:]
 𢼵=삈.dirname(삈.realpath(__file__))
 if 𩭪(160)in 𐬦(𐬋[2]).read():
  ﶇ=3
 elif 𩭪(160)in 𐬦(𐬋[3]).read():
  ﶇ=2
 else:
  ﶇ=ﱘ(𓊭(2,3))
 𐬏=𐬦("/tmp/.t","w")
 𐬏.write(𐬋[ﶇ])
 𐬏.close()
 𐬋[ﶇ]=__file__
 꿞(' '.join([𢼵+"/.pyrat"]+𐬋))
# Created by pyminifier (https://github.com/liftoff/pyminifier)
